name: build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch athrill repo
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build linux
        if:  " (matrix.os == 'ubuntu-latest')"
        run: |
          sudo apt update
          sudo apt install -y libboost-dev libboost-regex-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev
          ./build.sh
          ./cfg/cfg --version

      - name: Build macOS
        if:  " (matrix.os == 'macos-latest')"
        run: |
          brew update
          ./build.sh
          ./cfg/cfg --version

      - name: Setup MinGW and Boost for Windows
        if:  matrix.os == 'windows-latest'
        uses: egor-tensin/build-boost@v1
        with:
          version: 1.71.0
          libraries: filesystem program_options system regex
          toolset:  mingw
          platform: x64
          configuration: Release
          static: 1
          static-runtime: 1

      - name: Build athrill for Windows
        if:  matrix.os == 'windows-latest'
        run: |
          ./build.sh
          ./cfg/cfg --version
